### ISSUE TITLE
OC-02 Create a Board Class

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurChess#2]
A Board Class is a collection of cells, should it take a single value as a size? Should a board always be square? Why?

What if we want strange shaped boards ( like an hourglass?)

**Comment by JornPrengerFormeel** [comment]
maybe we could make more then 1, but do we play against an ai, if so... how?
if not, how do we do the turn each time someone played

**Comment by JornPrengerFormeel** [comment]
https://en.wikipedia.org/wiki/List_of_chess_variants here i found something about chess shapes

**Comment by joseph-allen** [comment]
nothing to worry about for now, lets start with board generic enough to play chess or checkers. So we need a board made up of cells and cells need to be able to hold a "piece"

**Comment by JornPrengerFormeel** [comment]
how do you think to create a load of cells, with a grid?

**Comment by joseph-allen** [comment]
yes. a Grid for Chess would be an 8x8 array or cells perhaps?
we should start with the cell class, although you coul make a grid of ints for now and we can change it later

**Comment by JornPrengerFormeel** [comment]
I am on that!

**Comment by FreedomGrenade** [comment]
Hey, I took this and put it in a board class. #7
